site :opscode

cookbook 'apt'
cookbook 'curl'
cookbook 'users'
cookbook 'chef-solo-search'
cookbook 'build-essential'
cookbook 'sudo'
cookbook 'rsync'
cookbook 'git'
cookbook 'ruby'
cookbook 'chef_gem'
cookbook 'chef-rvm', git: 'https://github.com/fnichol/chef-rvm.git'
cookbook 'vim'
cookbook 'zsh'
cookbook 'oh-my-zsh'
cookbook 'tmux'
cookbook 'rvm'
cookbook 'byobu'
cookbook 'virtalbox', git: 'git@github.com:bradleyd/virtualbox-cookbook.git'
cookbook 'nginx'
cookbook 'smbfs'
cookbook 'packer'
cookbook 'mariadb', git: 'git@github.com:tett23/chef-mariadb.git'
cookbook 'openssl'
cookbook "groonga", github: "groonga/chef-cookbooks", rel: "groonga"
